### ISSUE TITLE
Make the items returned from Generate Sheet display in alphabetical order

### ISSUE THREAD

**Issue by ileshmistry** [Kentico/kontent-google-sheets-add-on#13]
It would be really good to see the list of Content Types in alphabetical order when you go to Generate Sheet, as at the moment if you have a lot of Content Types, it's hard to find the one you want. Having them in alphabetical order will really speed up this process.

**Comment by kentico-ericd** [comment]
Good idea 👍 Done!

**Comment by ileshmistry** [comment]
Thanks :)
