### ISSUE TITLE
Support for assets

### ISSUE THREAD

**Issue by Isetnofret1** [Kentico/kontent-google-sheets-add-on#2]
Please include support for Asset field types for import using the google sheet import addon.
The required value would be:
"value": [
  {
    "id": "6c332099-56fb-46df-95e7-2db2983a1ea3"
  }
]

but is not currently supported.  I think it would make most sense to just have the import accept a GUID value.

**Comment by kentico-ericd** [comment]
Hello @Isetnofret1, thank you for the submission! I've just updated the add-on to v12 with Asset element support. Your add-on should auto-update, but just in case it doesn't work you can re-install it from the Marketplace: https://gsuite.google.com/marketplace/app/kentico_kontent/482429381322.

The format for updating Asset elements is described here:
https://github.com/Kentico/kontent-google-sheets-add-on#formatting-cell-values. Let me know if it works for you!

**Comment by Isetnofret1** [comment]
Works like a charm! Thank you!!!
