### ISSUE TITLE
Configuration not saving

### ISSUE THREAD

**Issue by Isetnofret1** [Kentico/kontent-google-sheets-add-on#3]
**Describe the bug**
Configuration not saving in google sheets.

**To Reproduce**
1. Go to google sheets
2. Click on configure
3. Enter API information
4. Click save and never updates the information just sits on a gray save button.

**Expected behavior**
Should have saved information in configuration. Just sits there not updating anything.

**Screenshots**

![image](https://user-images.githubusercontent.com/55595141/76788897-2b720400-6792-11ea-9a34-f781501209cb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Latest Chrome
 - Version 80.0.3987.132

**Comment by Simply007** [comment]
@kentico-ericd  - could you take a look?

**Comment by kentico-ericd** [comment]
@Isetnofret1 I'm afraid I couldn't reproduce the issue on Chrome 80 and Win10- it works every time. Can you check your browser's **Console** for errors, or the **Network** tab to see if there's any stuck/failed requests?

Also, can you try in an Incognito window without extensions?
